version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:590184032575:task-definition/helloWorldTaskDef:1"
        LoadBalancerInfo:
          ContainerName: "helloWorldRestApi"
          ContainerPort: "80"
        PlatformVersion: "LATEST"